### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by rien333** [digitronik/python-xrectsel#9]
No matter how I call the program, it always just errors for me. 

```
$ python --version
Python 3.9.7
$ uname -mor
5.14.14-arch1-1 x86_64 GNU/Linux
```

Error:

```
Traceback (most recent call last):
  File "/usr/bin/xrectsel", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3.9/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2303, in process_value
    value = self.type_cast_value(ctx, value)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2291, in type_cast_value
    return convert(value)
  File "/usr/lib/python3.9/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/usr/lib/python3.9/site-packages/click/types.py", line 399, in convert
    return self._number_class(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

**Comment by ulidtko** [comment]
Hi all, had same issue, this is easy to fix — PR #10 submitted — please review & approve to merge

@digitronik please merge
